### ISSUE TITLE
Создание одного канала Location вместо 2-х Long/Lat

### ISSUE THREAD

**Issue by LazyGatto** [d51x/org.openhab.binding.pandoracaralarmsystem#2]
На текущий момент биндинг создает два канала:
1. telemetry#lat (Number)
2. telemetry#lon (Number)

Есть предложение на уровне биндинга объединить их в один канал сразу, где будет просто склейка двух этих значений и сразу отдаваться тип канала/Item Location.
По типу: 
```
telemetry#lat + ',' + telemetry#lon
```
Например,
telemetry#location (Location)

**Comment by d51x** [comment]
added in 76d598b8e454832d5eff8b5ead4eaef89e8f0f58
