### ISSUE TITLE
Создание доп канала telemetry#mileage_CAN

### ISSUE THREAD

**Issue by LazyGatto** [d51x/org.openhab.binding.pandoracaralarmsystem#3]
Пандора отдает еще один параметр, пробег считанный по CAN.
Просьба добавить еще один канал с данными ;)
`telemetry#mileage_CAN`
Спасибо большое.
```
"mileage": 34784.81880944512,
"mileage_CAN": 40118,

```

**Comment by d51x** [comment]
added in f4cff2b5e16cba2029de2ededfc8b119bea8d1d6
